[project]
name = "dagster-template"
version = "1"
requires-python = ">3.10"
dependencies = ["dagster", "dagit", "pandas"]

[project.optional-dependencies]
dev = ["pytest", "black", "flake8", "mypy", "types-requests"]
